#!/usr/bin/env node
// Copyright (c) 2026 Morgott
// Licensed under CC BY-NC 4.0 — see LICENSE.

import { createInterface } from "node:readline";
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { execSync, execFileSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { CookieExtractor } from "./clients/cookie-extractor.js";
import { WebClient } from "./clients/web-client.js";
import { NexusApiClient } from "./clients/nexus-api.js";
import { loadConfig } from "./config.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ENV_PATH = path.resolve(ROOT, ".env");
const API_KEY_URL = "https://www.nexusmods.com/users/myaccount?tab=api";

const rl = createInterface({ input: process.stdin, output: process.stderr });
const ask = (q: string) => new Promise<string>((resolve) => rl.question(q, (a) => resolve(a.trim())));
const say = (s = "") => console.error(s);

function openUrl(url: string): void {
  say(`\n  → ${url}\n`);
  try {
    if (process.platform === "darwin") execFileSync("open", [url], { stdio: "ignore", timeout: 5000 });
    // `start` treats the first quoted token as the window title, hence the empty "".
    else if (process.platform === "win32") execFileSync("cmd", ["/c", "start", "", url], { stdio: "ignore", timeout: 5000, windowsHide: true });
    else execFileSync("xdg-open", [url], { stdio: "ignore", timeout: 5000 });
  } catch {
    // URL already printed
  }
}

function loadEnv(): Record<string, string> {
  const env: Record<string, string> = {};
  if (!existsSync(ENV_PATH)) return env;
  for (const line of readFileSync(ENV_PATH, "utf-8").split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const eq = t.indexOf("=");
    if (eq > 0) env[t.slice(0, eq)] = t.slice(eq + 1);
  }
  return env;
}

function saveEnv(env: Record<string, string>): void {
  const known = ["NEXUS_API_KEY", "NEXUS_DOWNLOAD_DIR", "NEXUS_UPLOAD_DIR"];
  const lines = ["# Nexus Mods MCP Server configuration", "# Generated by: npm run setup", ""];
  for (const k of known) lines.push(`${k}=${env[k] ?? ""}`);
  for (const [k, v] of Object.entries(env)) if (!known.includes(k)) lines.push(`${k}=${v}`);
  writeFileSync(ENV_PATH, lines.join("\n") + "\n");
}

async function stepApiKey(env: Record<string, string>): Promise<void> {
  say("━━━ Step 1/2: Personal API key (mods, files, downloads, tracking, uploads) ━━━\n");
  if (env.NEXUS_API_KEY) {
    say(`  ✓ Already configured: ${env.NEXUS_API_KEY.slice(0, 6)}...`);
    if ((await ask("  Replace it? (y/N): ")).toLowerCase() !== "y") return say();
  }
  say("  Open your account's API page, scroll to 'Personal API Key', copy it:");
  openUrl(API_KEY_URL);
  const key = await ask("  Paste your API key (or Enter to skip): ");
  if (!key) return say("  → Skipped. GraphQL tools (search, collections, users) still work without a key.\n");
  try {
    const u = await new NexusApiClient(key).v1("GET", "/users/validate");
    say(`  ✓ Valid — ${u.name} (premium: ${u.is_premium ? "yes" : "no"})`);
    env.NEXUS_API_KEY = key;
  } catch (e) {
    say(`  ✗ Key rejected: ${e instanceof Error ? e.message : e}`);
    if ((await ask("  Save it anyway? (y/N): ")).toLowerCase() === "y") env.NEXUS_API_KEY = key;
  }
  say();
}

async function stepWeb(): Promise<void> {
  say("━━━ Step 2/2: Web session (optional — posting mod/collection comments) ━━━\n");
  say("  Reading mod comments and forums works without this. POSTING comments is not");
  say("  possible through the official API without OAuth, so it uses an UNOFFICIAL workaround:");
  say("    • your nexusmods.com session cookies are read from your browser, or you sign in");
  say("      once in a dedicated browser window (kept in ~/.nexusmods-mcp/chrome-profile);");
  say("    • requests then run through that headless browser, like the website itself.");
  say("  Not endorsed by Nexus Mods; may break if the site changes.\n");
  if ((await ask("  Enable the web session? (y/N): ")).toLowerCase() !== "y") {
    return say("  Skipped. Enable later with the web_login tool.\n");
  }

  say("  Preparing browser (one-time ~110MB download on first run)...");
  try {
    execSync("npx patchright install chromium", { cwd: ROOT, stdio: "pipe" });
    say("  ✓ Browser ready.");
  } catch {
    say("  ⚠ Could not pre-install the bundled browser; will try anyway.");
  }

  const web = new WebClient(loadConfig());
  try {
    const extracted = await new CookieExtractor().extractCookies();
    if (extracted.cookies.length) {
      web.setCookiesFromString(extracted.cookies.map((c) => `${c.name}=${c.value}`).join("; "));
      if ((await web.whoAmI()).loggedIn) {
        say(`  ✓ Logged in using cookies from ${extracted.browser}.\n`);
        return;
      }
    }
    say("  No usable browser session found (normal on Windows Chrome 127+).");
    if ((await ask("  Sign in once in a dedicated browser window now? (Y/n): ")).toLowerCase().startsWith("n")) {
      return say("  Skipped. Use the web_login tool later.\n");
    }
    const ok = await web.loginInteractive();
    say(ok ? "  ✓ Logged in — session saved.\n" : "  ✗ Login timed out. Retry later with the web_login tool.\n");
  } catch (e) {
    say(`  ✗ ${e instanceof Error ? e.message : e}\n`);
  } finally {
    await web.close();
  }
}

async function main(): Promise<void> {
  say("\n  Nexus Mods MCP Server — Setup\n");
  const env = loadEnv();
  await stepApiKey(env);
  saveEnv(env);
  await stepWeb();

  if (!existsSync(path.join(ROOT, "build", "index.js"))) {
    say("━━━ Building server... ━━━");
    try {
      execSync("npm run build", { cwd: ROOT, stdio: "inherit" });
    } catch {
      say("  ⚠ Build failed — run 'npm run build' in the project dir.");
    }
  }
  say(`  API key: ${env.NEXUS_API_KEY ? "✓" : "✗"}   Web session: ${existsSync(loadConfig().cookiesPath) ? "✓" : "✗"}`);
  say("  Restart your AI client to activate.\n");
  rl.close();
}

main().catch((err) => {
  console.error("Error:", err);
  rl.close();
  process.exit(1);
});
